[package]
name = "rust_os"
version = "0.1.0"
authors = ["DotTorrent <pointtorrent@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlibc = "1.0.0"
bootloader = "0.9.8"

# Abort on panic to disabled stack unwinding
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
